//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asegurado
    {
        public Asegurado()
        {
            this.DetallePagoes = new HashSet<DetallePago>();
            this.Incapacidades = new HashSet<Incapacidade>();
            this.Movimientos = new HashSet<Movimiento>();
            this.MovimientosAseguradoes = new HashSet<MovimientosAsegurado>();
            this.ReporteConMeses = new HashSet<ReporteConMes>();
        }
    
        public int id { get; set; }
        public string numeroAfiliacion { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> salarioImss { get; set; }
        public Nullable<decimal> salarioInfo { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public string tipoTrabajo { get; set; }
        public string semanaJornada { get; set; }
        public string paginaInfo { get; set; }
        public string tipoDescuento { get; set; }
        public Nullable<decimal> valorDescuento { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string nombreTemporal { get; set; }
        public Nullable<System.DateTime> fechaDescuento { get; set; }
        public Nullable<System.DateTime> finDescuento { get; set; }
        public string articulo33 { get; set; }
        public Nullable<decimal> salarioArticulo33 { get; set; }
        public string trapeniv { get; set; }
        public string estado { get; set; }
        public string claveMunicipio { get; set; }
        public int PatroneId { get; set; }
        public string extranjero { get; set; }
        public string ocupacion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string alta { get; set; }
        public string baja { get; set; }
        public string modificacion { get; set; }
        public string permanente { get; set; }
        public int Plaza_id { get; set; }
        public Nullable<decimal> salarioDiario { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string nombres { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<DetallePago> DetallePagoes { get; set; }
        public virtual ICollection<Incapacidade> Incapacidades { get; set; }
        public virtual ICollection<Movimiento> Movimientos { get; set; }
        public virtual ICollection<MovimientosAsegurado> MovimientosAseguradoes { get; set; }
        public virtual Patrone Patrone { get; set; }
        public virtual Plaza Plaza { get; set; }
        public virtual ICollection<ReporteConMes> ReporteConMeses { get; set; }
    }
}
