//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoMovimiento1
    {
        public CatalogoMovimiento1()
        {
            this.MovimientosAseguradoes = new HashSet<MovimientosAsegurado>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual ICollection<MovimientosAsegurado> MovimientosAseguradoes { get; set; }
    }
}
