//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Acreditados = new HashSet<Acreditado>();
            this.Asegurados = new HashSet<Asegurado>();
            this.ContratosClientes = new HashSet<ContratosCliente>();
            this.DatosAdicionalesClientes = new HashSet<DatosAdicionalesCliente>();
            this.ListaValidacionClientes = new HashSet<ListaValidacionCliente>();
            this.Solicituds = new HashSet<Solicitud>();
            this.Proyectos = new HashSet<Proyecto>();
            this.ReporteConMeses = new HashSet<ReporteConMes>();
            this.SDIs = new HashSet<SDI>();
            this.SumarizadoClientes = new HashSet<SumarizadoCliente>();
        }
    
        public int Id { get; set; }
        public string claveCliente { get; set; }
        public string claveSua { get; set; }
        public string rfc { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
        public string direccionFiscal { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
        public string direccionOficina { get; set; }
        public string email { get; set; }
        public string actividadPrincipal { get; set; }
        public Nullable<System.DateTime> fechaContratacion { get; set; }
        public Nullable<int> empresaFacturadoraId { get; set; }
        public Nullable<int> ejecutivoContadorId { get; set; }
        public int Plaza_id { get; set; }
        public int Grupo_id { get; set; }
        public Nullable<int> tipoClienteId { get; set; }
        public string numeroCuenta { get; set; }
        public Nullable<int> tipoServicioId { get; set; }
    
        public virtual ICollection<Acreditado> Acreditados { get; set; }
        public virtual ICollection<Asegurado> Asegurados { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual Plaza Plaza { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<ContratosCliente> ContratosClientes { get; set; }
        public virtual ICollection<DatosAdicionalesCliente> DatosAdicionalesClientes { get; set; }
        public virtual ICollection<ListaValidacionCliente> ListaValidacionClientes { get; set; }
        public virtual ICollection<Solicitud> Solicituds { get; set; }
        public virtual ICollection<Proyecto> Proyectos { get; set; }
        public virtual ICollection<ReporteConMes> ReporteConMeses { get; set; }
        public virtual ICollection<SDI> SDIs { get; set; }
        public virtual ICollection<SumarizadoCliente> SumarizadoClientes { get; set; }
    }
}
