//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public Concepto()
        {
            this.ArchivoEmpleadoes = new HashSet<ArchivoEmpleado>();
            this.DocumentoEmpleadoes = new HashSet<DocumentoEmpleado>();
            this.FamiliaresEmpleadoes = new HashSet<FamiliaresEmpleado>();
            this.RespuestaSolicituds = new HashSet<RespuestaSolicitud>();
            this.SalarialesEmpleadoes = new HashSet<SalarialesEmpleado>();
            this.Solicituds = new HashSet<Solicitud>();
            this.Solicituds1 = new HashSet<Solicitud>();
            this.Solicituds2 = new HashSet<Solicitud>();
            this.Solicituds3 = new HashSet<Solicitud>();
            this.Solicituds4 = new HashSet<Solicitud>();
            this.Solicituds5 = new HashSet<Solicitud>();
            this.ArchivosEmpleados = new HashSet<ArchivosEmpleado>();
            this.documentosEmpleadoes = new HashSet<documentosEmpleado>();
            this.RespuestaSolicituds1 = new HashSet<RespuestaSolicitud1>();
            this.Solicituds6 = new HashSet<Solicitud1>();
            this.Solicituds11 = new HashSet<Solicitud1>();
            this.Solicituds21 = new HashSet<Solicitud1>();
            this.Solicituds31 = new HashSet<Solicitud1>();
            this.Solicituds41 = new HashSet<Solicitud1>();
            this.Solicituds51 = new HashSet<Solicitud1>();
        }
    
        public int id { get; set; }
        public string grupo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int usuarioId { get; set; }
        public int usuaNvarioId { get; set; }
    
        public virtual ICollection<ArchivoEmpleado> ArchivoEmpleadoes { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<DocumentoEmpleado> DocumentoEmpleadoes { get; set; }
        public virtual ICollection<FamiliaresEmpleado> FamiliaresEmpleadoes { get; set; }
        public virtual ICollection<RespuestaSolicitud> RespuestaSolicituds { get; set; }
        public virtual ICollection<SalarialesEmpleado> SalarialesEmpleadoes { get; set; }
        public virtual ICollection<Solicitud> Solicituds { get; set; }
        public virtual ICollection<Solicitud> Solicituds1 { get; set; }
        public virtual ICollection<Solicitud> Solicituds2 { get; set; }
        public virtual ICollection<Solicitud> Solicituds3 { get; set; }
        public virtual ICollection<Solicitud> Solicituds4 { get; set; }
        public virtual ICollection<Solicitud> Solicituds5 { get; set; }
        public virtual ICollection<ArchivosEmpleado> ArchivosEmpleados { get; set; }
        public virtual ICollection<documentosEmpleado> documentosEmpleadoes { get; set; }
        public virtual ICollection<RespuestaSolicitud1> RespuestaSolicituds1 { get; set; }
        public virtual ICollection<Solicitud1> Solicituds6 { get; set; }
        public virtual ICollection<Solicitud1> Solicituds11 { get; set; }
        public virtual ICollection<Solicitud1> Solicituds21 { get; set; }
        public virtual ICollection<Solicitud1> Solicituds31 { get; set; }
        public virtual ICollection<Solicitud1> Solicituds41 { get; set; }
        public virtual ICollection<Solicitud1> Solicituds51 { get; set; }
        public virtual UsuaNvario UsuaNvario { get; set; }
    }
}
