//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public Concepto()
        {
            this.ArchivosEmpleados = new HashSet<ArchivosEmpleado>();
            this.DocumentosEmpleadoes = new HashSet<DocumentosEmpleado>();
            this.FamiliaresEmpleadoes = new HashSet<FamiliaresEmpleado>();
            this.RespuestaSolicituds = new HashSet<RespuestaSolicitud>();
            this.SalarialesEmpleadoes = new HashSet<SalarialesEmpleado>();
            this.Solicituds = new HashSet<Solicitud>();
            this.Solicituds1 = new HashSet<Solicitud>();
            this.Solicituds2 = new HashSet<Solicitud>();
            this.Solicituds3 = new HashSet<Solicitud>();
            this.Solicituds4 = new HashSet<Solicitud>();
            this.Solicituds5 = new HashSet<Solicitud>();
            this.SolicitudEmpleadoes = new HashSet<SolicitudEmpleado>();
            this.SolicitudPrenominas = new HashSet<SolicitudPrenomina>();
            this.SolicitudPrenominas1 = new HashSet<SolicitudPrenomina>();
            this.SolicitudPrenominas2 = new HashSet<SolicitudPrenomina>();
            this.SolicitudPrenominas3 = new HashSet<SolicitudPrenomina>();
        }
    
        public int id { get; set; }
        public string grupo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int usuarioId { get; set; }
    
        public virtual ICollection<ArchivosEmpleado> ArchivosEmpleados { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<DocumentosEmpleado> DocumentosEmpleadoes { get; set; }
        public virtual ICollection<FamiliaresEmpleado> FamiliaresEmpleadoes { get; set; }
        public virtual ICollection<RespuestaSolicitud> RespuestaSolicituds { get; set; }
        public virtual ICollection<SalarialesEmpleado> SalarialesEmpleadoes { get; set; }
        public virtual ICollection<Solicitud> Solicituds { get; set; }
        public virtual ICollection<Solicitud> Solicituds1 { get; set; }
        public virtual ICollection<Solicitud> Solicituds2 { get; set; }
        public virtual ICollection<Solicitud> Solicituds3 { get; set; }
        public virtual ICollection<Solicitud> Solicituds4 { get; set; }
        public virtual ICollection<Solicitud> Solicituds5 { get; set; }
        public virtual ICollection<SolicitudEmpleado> SolicitudEmpleadoes { get; set; }
        public virtual ICollection<SolicitudPrenomina> SolicitudPrenominas { get; set; }
        public virtual ICollection<SolicitudPrenomina> SolicitudPrenominas1 { get; set; }
        public virtual ICollection<SolicitudPrenomina> SolicitudPrenominas2 { get; set; }
        public virtual ICollection<SolicitudPrenomina> SolicitudPrenominas3 { get; set; }
    }
}
