//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratosCliente
    {
        public int id { get; set; }
        public int clienteId { get; set; }
        public string descripcion { get; set; }
        public string archivo1 { get; set; }
        public string archivo2 { get; set; }
        public string archivo3 { get; set; }
        public string actaConstitutivaEmpresa { get; set; }
        public string poderRepresentanteLegal { get; set; }
        public string ifeRepresentanteLegal { get; set; }
        public string comprobanteDomicilio { get; set; }
        public Nullable<System.DateTime> fechaInicioVigencia { get; set; }
        public Nullable<System.DateTime> fechaFinalVigencia { get; set; }
        public string estatus { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int usuarioId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
