//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaEmpleado
    {
        public CuentaEmpleado()
        {
            this.DetallePrenominas = new HashSet<DetallePrenomina>();
        }
    
        public int id { get; set; }
        public int empleadoId { get; set; }
        public int bancoId { get; set; }
        public string cuenta { get; set; }
        public string cuentaClabe { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int usuarioId { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<DetallePrenomina> DetallePrenominas { get; set; }
    }
}
