//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosAdicionalesCliente
    {
        public int id { get; set; }
        public int clienteId { get; set; }
        public Nullable<decimal> porcentajeComNomina { get; set; }
        public Nullable<decimal> ivaNomina { get; set; }
        public Nullable<decimal> porcentajeComIAS { get; set; }
        public Nullable<decimal> ivaIAS { get; set; }
        public Nullable<decimal> porcentajeComFlujo { get; set; }
        public Nullable<decimal> ivaFlujo { get; set; }
        public Nullable<decimal> costoSocial { get; set; }
        public Nullable<int> conceptoFacturacion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int usuarioId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
