//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePago
    {
        public int @int { get; set; }
        public int pagoId { get; set; }
        public string periodo { get; set; }
        public string nss { get; set; }
        public string rfc { get; set; }
        public string curp { get; set; }
        public string creditoInfonavit { get; set; }
        public string fid { get; set; }
        public string trabajador { get; set; }
        public string sdi { get; set; }
        public string tipoTrabajador { get; set; }
        public string jornadaSemanaReducida { get; set; }
        public string diasCotizadosMes { get; set; }
        public string diasIncapacidad { get; set; }
        public string diasAusentismo { get; set; }
        public Nullable<decimal> cuotaFija { get; set; }
        public Nullable<decimal> cuotaExcendente { get; set; }
        public Nullable<decimal> prestacionesDinero { get; set; }
        public Nullable<decimal> gastosMedicosPensionados { get; set; }
        public Nullable<decimal> riesgoTrabajo { get; set; }
        public Nullable<decimal> invalidezVida { get; set; }
        public Nullable<int> guarderias { get; set; }
        public Nullable<decimal> actRecargosImss { get; set; }
        public string diasCotizadosBimestre { get; set; }
        public string diasIncapacidadBimestre { get; set; }
        public string diasAusentismoBimestre { get; set; }
        public Nullable<int> retiro { get; set; }
        public Nullable<decimal> actRecargosRetiro { get; set; }
        public Nullable<decimal> cesantiaVejezPatronal { get; set; }
        public Nullable<decimal> cesantiaVejezObrera { get; set; }
        public Nullable<decimal> actRecargosCyV { get; set; }
        public Nullable<decimal> aportacionVoluntaria { get; set; }
        public Nullable<decimal> aportacionComp { get; set; }
        public Nullable<decimal> aportacionPatronal { get; set; }
        public Nullable<decimal> amortizacion { get; set; }
        public string actImss { get; set; }
        public string recImss { get; set; }
        public string actRetiro { get; set; }
        public string recRetiro { get; set; }
        public string actCesPat { get; set; }
        public string recCesPat { get; set; }
        public string actCesObr { get; set; }
        public string recCesObr { get; set; }
        public Nullable<decimal> cuotaExcObr { get; set; }
        public Nullable<decimal> cuotaPdObr { get; set; }
        public Nullable<decimal> cuotaGmpObr { get; set; }
        public Nullable<decimal> cuotaIvObr { get; set; }
        public string actPatImss { get; set; }
        public string recPatImss { get; set; }
        public string actObrImss { get; set; }
        public string recObrImss { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int usuarioId { get; set; }
    
        public virtual Pago Pago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
