//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosEmpleado
    {
        public int id { get; set; }
        public int empleadoId { get; set; }
        public string actividades { get; set; }
        public string domicilioOficina { get; set; }
        public System.DateTime fechaAntiguedad { get; set; }
        public Nullable<decimal> salarioVSM { get; set; }
        public int jornadaLaboralId { get; set; }
        public Nullable<int> diasDescanso { get; set; }
        public decimal salarioNominal { get; set; }
        public Nullable<int> diasVacaciones { get; set; }
        public Nullable<int> diasAguinaldo { get; set; }
        public string otros { get; set; }
        public string telefono { get; set; }
        public string tipoSangre { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int usuarioId { get; set; }
    
        public virtual Concepto Concepto { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
