//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factore
    {
        public int id { get; set; }
        public Nullable<int> anosTrabajados { get; set; }
        public Nullable<int> diasVacaciones { get; set; }
        public Nullable<decimal> primaVacacional { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public Nullable<int> diasAno { get; set; }
        public Nullable<decimal> factorVacaciones { get; set; }
        public Nullable<int> aguinaldo { get; set; }
        public Nullable<int> diasAnoAguinaldo { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<decimal> factorIntegracion { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int usuarioId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
