//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcion
    {
        public Funcion()
        {
            this.RoleFuncions = new HashSet<RoleFuncion>();
        }
    
        public int id { get; set; }
        public int moduloId { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionLarga { get; set; }
        public string accion { get; set; }
        public string controlador { get; set; }
        public string estatus { get; set; }
        public int usuarioId { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string tipo { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual ICollection<RoleFuncion> RoleFuncions { get; set; }
    }
}
