//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        public Grupos()
        {
            this.Clientes = new HashSet<Cliente>();
        }
    
        public int Id { get; set; }
        public string claveGrupo { get; set; }
        public string nombre { get; set; }
        public string nombreCorto { get; set; }
        public int Plaza_id { get; set; }
        public string posicion { get; set; }
        public string estatus { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual Plaza Plaza { get; set; }
    }
}
