//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incapacidade
    {
        public Incapacidade()
        {
            this.MovimientosAseguradoes = new HashSet<MovimientosAsegurado>();
        }
    
        public int id { get; set; }
        public int aseguradoId { get; set; }
        public System.DateTime fechaAcc { get; set; }
        public string folioIncapacidad { get; set; }
        public string grupoIncapacidad { get; set; }
        public string recRev { get; set; }
        public string consecuencia { get; set; }
        public string tieRie { get; set; }
        public string ramSeq { get; set; }
        public string secuela { get; set; }
        public string conInc { get; set; }
        public int diaSub { get; set; }
        public decimal porcentajeIncapacidad { get; set; }
        public string indDef { get; set; }
        public System.DateTime fecTer { get; set; }
        public string tipoIncapacidad { get; set; }
        public string alta { get; set; }
    
        public virtual Asegurado Asegurado { get; set; }
        public virtual ICollection<MovimientosAsegurado> MovimientosAseguradoes { get; set; }
    }
}
