//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.Funcions = new HashSet<Funcion>();
            this.RoleModulos = new HashSet<RoleModulo>();
        }
    
        public int id { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionLarga { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string estatus { get; set; }
    
        public virtual ICollection<Funcion> Funcions { get; set; }
        public virtual ICollection<RoleModulo> RoleModulos { get; set; }
    }
}
