//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int id { get; set; }
        public Nullable<int> aseguradoId { get; set; }
        public Nullable<int> acreditadoId { get; set; }
        public string lote { get; set; }
        public System.DateTime fechaTransaccion { get; set; }
        public string tipo { get; set; }
        public string nombreArchivo { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual Acreditado Acreditado { get; set; }
        public virtual Asegurado Asegurado { get; set; }
    }
}
