//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosAsegurado
    {
        public int id { get; set; }
        public int aseguradoId { get; set; }
        public int movimientoId { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public string sdi { get; set; }
        public Nullable<int> numeroDias { get; set; }
        public string folio { get; set; }
        public int incapacidadId { get; set; }
        public string credito { get; set; }
        public string estatus { get; set; }
    
        public virtual Asegurado Asegurado { get; set; }
        public virtual CatalogoMovimiento CatalogoMovimiento { get; set; }
        public virtual Incapacidade Incapacidade { get; set; }
    }
}
