//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        public Municipio()
        {
            this.Empleados = new HashSet<Empleado>();
        }
    
        public int id { get; set; }
        public int paisId { get; set; }
        public int estadoId { get; set; }
        public string entidad { get; set; }
        public string municipio1 { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
        public string nomTipo { get; set; }
        public string region { get; set; }
        public string gradoMarginacion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int usuarioId { get; set; }
    
        public virtual ICollection<Empleado> Empleados { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
