//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public Pago()
        {
            this.DetallePagoes = new HashSet<DetallePago>();
            this.ResumenPagoes = new HashSet<ResumenPago>();
        }
    
        public int id { get; set; }
        public decimal imss { get; set; }
        public decimal rcv { get; set; }
        public decimal infonavit { get; set; }
        public decimal total { get; set; }
        public decimal recargos { get; set; }
        public decimal actualizaciones { get; set; }
        public decimal granTotal { get; set; }
        public Nullable<System.DateTime> fechaDeposito { get; set; }
        public Nullable<int> bancoId { get; set; }
        public Nullable<int> nt { get; set; }
        public string comprobantePago { get; set; }
        public string resumenLiquidacion { get; set; }
        public string cedulaAutodeterminacion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int usuarioId { get; set; }
        public int patronId { get; set; }
        public string mes { get; set; }
        public string anno { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual ICollection<DetallePago> DetallePagoes { get; set; }
        public virtual Patrone Patrone { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<ResumenPago> ResumenPagoes { get; set; }
    }
}
