//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Empleados = new HashSet<Empleado>();
            this.Estados = new HashSet<Estado>();
            this.Municipios = new HashSet<Municipio>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string clavePais { get; set; }
        public string naturalez { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int usuarioId { get; set; }
    
        public virtual ICollection<Empleado> Empleados { get; set; }
        public virtual ICollection<Estado> Estados { get; set; }
        public virtual ICollection<Municipio> Municipios { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
