//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int id { get; set; }
        public string parametroId { get; set; }
        public string descripcion { get; set; }
        public string valorString { get; set; }
        public Nullable<decimal> valorMoneda { get; set; }
        public Nullable<System.DateTime> valorFecha { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    }
}
