//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plaza
    {
        public Plaza()
        {
            this.Acreditados = new HashSet<Acreditado>();
            this.Asegurados = new HashSet<Asegurado>();
            this.Clientes = new HashSet<Cliente>();
            this.Grupos = new HashSet<Grupos>();
            this.Patrones = new HashSet<Patrone>();
            this.Solicituds = new HashSet<Solicitud>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string cveCorta { get; set; }
        public string indicador { get; set; }
    
        public virtual ICollection<Acreditado> Acreditados { get; set; }
        public virtual ICollection<Asegurado> Asegurados { get; set; }
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<Grupos> Grupos { get; set; }
        public virtual ICollection<Patrone> Patrones { get; set; }
        public virtual ICollection<Solicitud> Solicituds { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
