//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaRT
    {
        public int id { get; set; }
        public int registroPatronal { get; set; }
        public int anio { get; set; }
        public int mes { get; set; }
        public decimal primaRT1 { get; set; }
        public string nomMes { get; set; }
    }
}
