//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepCostoSocial
    {
        public int id { get; set; }
        public string numeroAfiliacion { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<int> diasCotizados { get; set; }
        public Nullable<double> salarioIMSS { get; set; }
        public string ubicacion { get; set; }
        public string grupo { get; set; }
        public string registroPatronal { get; set; }
        public string nombreRegPatronal { get; set; }
        public Nullable<decimal> IMSS { get; set; }
        public Nullable<decimal> RCV { get; set; }
        public Nullable<decimal> Infonavit { get; set; }
        public Nullable<decimal> totalCosto { get; set; }
        public Nullable<decimal> descuentoMensual { get; set; }
        public Nullable<decimal> impuestoSNomina { get; set; }
        public Nullable<decimal> porcNomina { get; set; }
        public Nullable<decimal> porcCotizado { get; set; }
        public Nullable<decimal> totalCostoSocial { get; set; }
        public string numeroCredito { get; set; }
        public Nullable<decimal> descuentoCatorcenal { get; set; }
        public Nullable<decimal> descuentoQuincenal { get; set; }
        public Nullable<decimal> descuentoVeintiochonal { get; set; }
        public Nullable<decimal> descuentoDiario { get; set; }
        public Nullable<decimal> descuentoSemanal { get; set; }
        public Nullable<int> usuarioId { get; set; }
    }
}
