//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteConMes
    {
        public int id { get; set; }
        public Nullable<int> patronId { get; set; }
        public Nullable<int> aseguradoId { get; set; }
        public string anno { get; set; }
        public string mes { get; set; }
        public Nullable<decimal> enero { get; set; }
        public Nullable<decimal> febrero { get; set; }
        public Nullable<decimal> marzo { get; set; }
        public Nullable<decimal> abril { get; set; }
        public Nullable<decimal> mayo { get; set; }
        public Nullable<decimal> junio { get; set; }
        public Nullable<decimal> julio { get; set; }
        public Nullable<decimal> agosto { get; set; }
        public Nullable<decimal> septiembre { get; set; }
        public Nullable<decimal> octubre { get; set; }
        public Nullable<decimal> noviembre { get; set; }
        public Nullable<decimal> diciembre { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> nt { get; set; }
        public int usuarioId { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int clienteId { get; set; }
    
        public virtual Asegurado Asegurado { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Patrone Patrone { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
