//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleModulo
    {
        public int id { get; set; }
        public int roleId { get; set; }
        public int moduloId { get; set; }
        public int usuarioCreacionId { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual Role Role { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
