//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public Solicitud()
        {
            this.Empleados = new HashSet<Empleado>();
            this.SolicitudEmpleadoes = new HashSet<SolicitudEmpleado>();
        }
    
        public int id { get; set; }
        public string folioSolicitud { get; set; }
        public int clienteId { get; set; }
        public int plazaId { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public Nullable<int> esquemaId { get; set; }
        public Nullable<int> sdiId { get; set; }
        public Nullable<int> contratoId { get; set; }
        public Nullable<System.DateTime> fechaTerminoContrato { get; set; }
        public Nullable<System.DateTime> fechaInicial { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<int> tipoPersonalId { get; set; }
        public string solicita { get; set; }
        public string valida { get; set; }
        public string autoriza { get; set; }
        public int noTrabajadores { get; set; }
        public string observaciones { get; set; }
        public int estatusSolicitud { get; set; }
        public Nullable<int> estatusNomina { get; set; }
        public Nullable<int> estatusAfiliado { get; set; }
        public Nullable<int> estatusJuridico { get; set; }
        public Nullable<int> estatusTarjeta { get; set; }
        public int usuarioId { get; set; }
        public int proyectoId { get; set; }
        public Nullable<System.DateTime> fechaEnvio { get; set; }
        public int tipoSolicitud { get; set; }
        public Nullable<int> conceptoBaja { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Concepto Concepto { get; set; }
        public virtual Concepto Concepto1 { get; set; }
        public virtual Concepto Concepto2 { get; set; }
        public virtual Concepto Concepto3 { get; set; }
        public virtual Concepto Concepto4 { get; set; }
        public virtual Concepto Concepto5 { get; set; }
        public virtual ICollection<Empleado> Empleados { get; set; }
        public virtual EsquemasPago EsquemasPago { get; set; }
        public virtual Plaza Plaza { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual RespuestaSolicitud RespuestaSolicitud { get; set; }
        public virtual SDI SDI { get; set; }
        public virtual SDI SDI1 { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
        public virtual TipoPersonal TipoPersonal { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<SolicitudEmpleado> SolicitudEmpleadoes { get; set; }
    }
}
