//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPrenomina
    {
        public SolicitudPrenomina()
        {
            this.DetallePrenominas = new HashSet<DetallePrenomina>();
        }
    
        public int id { get; set; }
        public string folioSolicitud { get; set; }
        public int clienteId { get; set; }
        public int plazaId { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public System.DateTime fechaInicial { get; set; }
        public System.DateTime fechaFinal { get; set; }
        public System.DateTime fechaPago { get; set; }
        public string folioCliente { get; set; }
        public int tipoPagoId { get; set; }
        public int periodoId { get; set; }
        public int tipoContratoId { get; set; }
        public int monedaId { get; set; }
        public Nullable<decimal> tipoCambio { get; set; }
        public string solicita { get; set; }
        public string valida { get; set; }
        public string autoriza { get; set; }
        public int noTrabajadores { get; set; }
        public string observaciones { get; set; }
        public int estatusSolicitud { get; set; }
        public int proyectoId { get; set; }
        public string anno { get; set; }
        public Nullable<System.DateTime> fechaEnvio { get; set; }
        public int usuarioId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Concepto Concepto { get; set; }
        public virtual Concepto Concepto1 { get; set; }
        public virtual Concepto Concepto2 { get; set; }
        public virtual ICollection<DetallePrenomina> DetallePrenominas { get; set; }
        public virtual Plaza Plaza { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
