//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicosUsuaNvario
    {
        public int id { get; set; }
        public int topicoId { get; set; }
        public int usuaNvarioId { get; set; }
        public string tipo { get; set; }
        public int usuaNvarioCreacionId { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual UsuaNvario UsuaNvario { get; set; }
        public virtual UsuaNvario UsuaNvario1 { get; set; }
    }
}
