//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuaNvario
    {
        public UsuaNvario()
        {
            this.ArchivosEmpleados = new HashSet<ArchivosEmpleado>();
            this.Bancos = new HashSet<Banco>();
            this.Conceptos = new HashSet<Concepto>();
            this.ContratosClientes = new HashSet<ContratosCliente1>();
            this.DatosAdicionalesClientes = new HashSet<DatosAdicionalesCliente1>();
            this.Departamentos = new HashSet<Departamento>();
            this.DetallePagoes = new HashSet<DetallePago1>();
            this.documentosEmpleadoes = new HashSet<documentosEmpleado>();
            this.Empleados = new HashSet<Empleado>();
            this.Empresas = new HashSet<Empresa>();
            this.EsquemasPagoes = new HashSet<EsquemasPago1>();
            this.EstadoCivils = new HashSet<EstadoCivil1>();
            this.Estados = new HashSet<Estado>();
            this.Factores = new HashSet<Factore>();
            this.Giros = new HashSet<Giro>();
            this.ListaValidacionClientes = new HashSet<ListaValidacionCliente1>();
            this.Municipios = new HashSet<Municipio>();
            this.Pagos = new HashSet<Pago>();
            this.Paises = new HashSet<Pais>();
            this.RegimenInfonavits = new HashSet<RegimenInfonavit1>();
            this.Residencias = new HashSet<Residencia1>();
            this.RespuestaSolicituds = new HashSet<RespuestaSolicitud1>();
            this.ResumenPagoes = new HashSet<ResumenPago1>();
            this.RoleFuncions = new HashSet<RoleFuncion>();
            this.RoleModulos = new HashSet<RoleModulo>();
            this.SDIs = new HashSet<SDI>();
            this.Servicios = new HashSet<Servicio>();
            this.Sexos = new HashSet<Sexo>();
            this.Solicituds = new HashSet<Solicitud1>();
            this.SumarizadoClientes = new HashSet<SumarizadoCliente>();
            this.TipoContratoes = new HashSet<TipoContrato1>();
            this.TipoPersonals = new HashSet<TipoPersonal1>();
            this.TopicosUsuaNvarios = new HashSet<TopicosUsuaNvario>();
            this.TopicosUsuaNvarios1 = new HashSet<TopicosUsuaNvario>();
        }
    
        public int Id { get; set; }
        public string nombreUsuaNvario { get; set; }
        public string contrasena { get; set; }
        public string claveUsuaNvario { get; set; }
        public string email { get; set; }
        public string apellidoMaterno { get; set; }
        public string apellidoPaterno { get; set; }
        public string estatus { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public int roleId { get; set; }
        public int plazaId { get; set; }
        public Nullable<int> departamentoId { get; set; }
    
        public virtual ICollection<ArchivosEmpleado> ArchivosEmpleados { get; set; }
        public virtual ICollection<Banco> Bancos { get; set; }
        public virtual ICollection<Concepto> Conceptos { get; set; }
        public virtual ICollection<ContratosCliente1> ContratosClientes { get; set; }
        public virtual ICollection<DatosAdicionalesCliente1> DatosAdicionalesClientes { get; set; }
        public virtual ICollection<Departamento> Departamentos { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual ICollection<DetallePago1> DetallePagoes { get; set; }
        public virtual ICollection<documentosEmpleado> documentosEmpleadoes { get; set; }
        public virtual ICollection<Empleado> Empleados { get; set; }
        public virtual ICollection<Empresa> Empresas { get; set; }
        public virtual ICollection<EsquemasPago1> EsquemasPagoes { get; set; }
        public virtual ICollection<EstadoCivil1> EstadoCivils { get; set; }
        public virtual ICollection<Estado> Estados { get; set; }
        public virtual ICollection<Factore> Factores { get; set; }
        public virtual ICollection<Giro> Giros { get; set; }
        public virtual ICollection<ListaValidacionCliente1> ListaValidacionClientes { get; set; }
        public virtual ICollection<Municipio> Municipios { get; set; }
        public virtual ICollection<Pago> Pagos { get; set; }
        public virtual ICollection<Pais> Paises { get; set; }
        public virtual Plaza Plaza { get; set; }
        public virtual ICollection<RegimenInfonavit1> RegimenInfonavits { get; set; }
        public virtual ICollection<Residencia1> Residencias { get; set; }
        public virtual ICollection<RespuestaSolicitud1> RespuestaSolicituds { get; set; }
        public virtual ICollection<ResumenPago1> ResumenPagoes { get; set; }
        public virtual ICollection<RoleFuncion> RoleFuncions { get; set; }
        public virtual ICollection<RoleModulo> RoleModulos { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<SDI> SDIs { get; set; }
        public virtual ICollection<Servicio> Servicios { get; set; }
        public virtual ICollection<Sexo> Sexos { get; set; }
        public virtual ICollection<Solicitud1> Solicituds { get; set; }
        public virtual ICollection<SumarizadoCliente> SumarizadoClientes { get; set; }
        public virtual ICollection<TipoContrato1> TipoContratoes { get; set; }
        public virtual ICollection<TipoPersonal1> TipoPersonals { get; set; }
        public virtual ICollection<TopicosUsuaNvario> TopicosUsuaNvarios { get; set; }
        public virtual ICollection<TopicosUsuaNvario> TopicosUsuaNvarios1 { get; set; }
    }
}
