//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUAMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SUAMVC.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        public static string accion {
            get {
                return ResourceManager.GetString("accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acreditados.
        /// </summary>
        public static string acreditados {
            get {
                return ResourceManager.GetString("acreditados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acta Constitutiva Empresa.
        /// </summary>
        public static string actaConstitutivaEmpresa {
            get {
                return ResourceManager.GetString("actaConstitutivaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad Principal.
        /// </summary>
        public static string actividadPrincipal {
            get {
                return ResourceManager.GetString("actividadPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda Avanzada.
        /// </summary>
        public static string advanceSearch {
            get {
                return ResourceManager.GetString("advanceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string agregar {
            get {
                return ResourceManager.GetString("agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aguinaldo.
        /// </summary>
        public static string aguinaldo {
            get {
                return ResourceManager.GetString("aguinaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Años Trabajados.
        /// </summary>
        public static string anosTrabajados {
            get {
                return ResourceManager.GetString("anosTrabajados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        public static string apellidoMaterno {
            get {
                return ResourceManager.GetString("apellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        public static string apellidoPaterno {
            get {
                return ResourceManager.GetString("apellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo 1.
        /// </summary>
        public static string archivo1 {
            get {
                return ResourceManager.GetString("archivo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo 2.
        /// </summary>
        public static string archivo2 {
            get {
                return ResourceManager.GetString("archivo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo 3.
        /// </summary>
        public static string archivo3 {
            get {
                return ResourceManager.GetString("archivo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizador.
        /// </summary>
        public static string autorizador {
            get {
                return ResourceManager.GetString("autorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avanzar.
        /// </summary>
        public static string avanzar {
            get {
                return ResourceManager.GetString("avanzar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso Incapacidad.
        /// </summary>
        public static string avisoInc {
            get {
                return ResourceManager.GetString("avisoInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso Ret..
        /// </summary>
        public static string avisoRet {
            get {
                return ResourceManager.GetString("avisoRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string banco {
            get {
                return ResourceManager.GetString("banco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bancos.
        /// </summary>
        public static string bancos {
            get {
                return ResourceManager.GetString("bancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string bt_cancel {
            get {
                return ResourceManager.GetString("bt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string bt_exit {
            get {
                return ResourceManager.GetString("bt_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string bt_login {
            get {
                return ResourceManager.GetString("bt_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string bt_register {
            get {
                return ResourceManager.GetString("bt_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Datos Adicionales Cliente.
        /// </summary>
        public static string catDatAdCliente {
            get {
                return ResourceManager.GetString("catDatAdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de.
        /// </summary>
        public static string catde {
            get {
                return ResourceManager.GetString("catde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        public static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave Grupo.
        /// </summary>
        public static string claGrupo {
            get {
                return ResourceManager.GetString("claGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave Cliente.
        /// </summary>
        public static string claveCliente {
            get {
                return ResourceManager.GetString("claveCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave SUA.
        /// </summary>
        public static string claveSua {
            get {
                return ResourceManager.GetString("claveSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave Usuario.
        /// </summary>
        public static string claveUsuario {
            get {
                return ResourceManager.GetString("claveUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string cliente {
            get {
                return ResourceManager.GetString("cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente ID.
        /// </summary>
        public static string clienteId {
            get {
                return ResourceManager.GetString("clienteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SIAP.
        /// </summary>
        public static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IMSS 3.0.
        /// </summary>
        public static string company_subtitle {
            get {
                return ResourceManager.GetString("company_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobante de Domicilio.
        /// </summary>
        public static string comprobanteDomicilio {
            get {
                return ResourceManager.GetString("comprobanteDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus Solicitud.
        /// </summary>
        public static string concepDescripcion {
            get {
                return ResourceManager.GetString("concepDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus Nom..
        /// </summary>
        public static string concepDescripcion1 {
            get {
                return ResourceManager.GetString("concepDescripcion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus Jurídico.
        /// </summary>
        public static string concepDescripcion2 {
            get {
                return ResourceManager.GetString("concepDescripcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus Afil..
        /// </summary>
        public static string concepDescripcion3 {
            get {
                return ResourceManager.GetString("concepDescripcion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus Tarj..
        /// </summary>
        public static string concepDescripcion4 {
            get {
                return ResourceManager.GetString("concepDescripcion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto de Facturación.
        /// </summary>
        public static string concepFacturacion {
            get {
                return ResourceManager.GetString("concepFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto.
        /// </summary>
        public static string concepto {
            get {
                return ResourceManager.GetString("concepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        public static string consulta {
            get {
                return ResourceManager.GetString("consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Cliente.
        /// </summary>
        public static string contCliente {
            get {
                return ResourceManager.GetString("contCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string contrasena {
            get {
                return ResourceManager.GetString("contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato Cliente.
        /// </summary>
        public static string contratosClientes {
            get {
                return ResourceManager.GetString("contratosClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controlador.
        /// </summary>
        public static string controlador {
            get {
                return ResourceManager.GetString("controlador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo Social.
        /// </summary>
        public static string costSocial {
            get {
                return ResourceManager.GetString("costSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterio.
        /// </summary>
        public static string criterio {
            get {
                return ResourceManager.GetString("criterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta Bancaria.
        /// </summary>
        public static string cuentaBancaria {
            get {
                return ResourceManager.GetString("cuentaBancaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta Clave.
        /// </summary>
        public static string cuentaClabe {
            get {
                return ResourceManager.GetString("cuentaClabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuota Fija.
        /// </summary>
        public static string cuotaFija {
            get {
                return ResourceManager.GetString("cuotaFija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CURP.
        /// </summary>
        public static string curp {
            get {
                return ResourceManager.GetString("curp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave Corta.
        /// </summary>
        public static string cveCorta {
            get {
                return ResourceManager.GetString("cveCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Adicionales Cliente.
        /// </summary>
        public static string datAdiCliente {
            get {
                return ResourceManager.GetString("datAdiCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        public static string dep {
            get {
                return ResourceManager.GetString("dep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        public static string departamento {
            get {
                return ResourceManager.GetString("departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Bimestral.
        /// </summary>
        public static string descBimestral {
            get {
                return ResourceManager.GetString("descBimestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Catorcenal.
        /// </summary>
        public static string descCatorcenal {
            get {
                return ResourceManager.GetString("descCatorcenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Diario.
        /// </summary>
        public static string descDiario {
            get {
                return ResourceManager.GetString("descDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Mensual.
        /// </summary>
        public static string descMensual {
            get {
                return ResourceManager.GetString("descMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Corta.
        /// </summary>
        public static string desCorta {
            get {
                return ResourceManager.GetString("desCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion País.
        /// </summary>
        public static string descPais {
            get {
                return ResourceManager.GetString("descPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Quincenal.
        /// </summary>
        public static string descQuincenal {
            get {
                return ResourceManager.GetString("descQuincenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Semanal.
        /// </summary>
        public static string descSemanal {
            get {
                return ResourceManager.GetString("descSemanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Veintiochonal.
        /// </summary>
        public static string descVeintiocho {
            get {
                return ResourceManager.GetString("descVeintiocho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Larga.
        /// </summary>
        public static string desLarga {
            get {
                return ResourceManager.GetString("desLarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        public static string desProyecto {
            get {
                return ResourceManager.GetString("desProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        public static string detalle {
            get {
                return ResourceManager.GetString("detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles de.
        /// </summary>
        public static string detallesDe {
            get {
                return ResourceManager.GetString("detallesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días al Año.
        /// </summary>
        public static string diasAno {
            get {
                return ResourceManager.GetString("diasAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días Año Aguinaldo.
        /// </summary>
        public static string diasAnoAguinaldo {
            get {
                return ResourceManager.GetString("diasAnoAguinaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días de Vacaciones.
        /// </summary>
        public static string diasVacaciones {
            get {
                return ResourceManager.GetString("diasVacaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección Fiscal.
        /// </summary>
        public static string direccionFiscal {
            get {
                return ResourceManager.GetString("direccionFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de Oficina.
        /// </summary>
        public static string direccionOficina {
            get {
                return ResourceManager.GetString("direccionOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direección Fiscal.
        /// </summary>
        public static string direcFiscal {
            get {
                return ResourceManager.GetString("direcFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutivo.
        /// </summary>
        public static string ejecutivo {
            get {
                return ResourceManager.GetString("ejecutivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutivo Contador.
        /// </summary>
        public static string ejecutivoContador {
            get {
                return ResourceManager.GetString("ejecutivoContador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejercicio.
        /// </summary>
        public static string ejercicio {
            get {
                return ResourceManager.GetString("ejercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string eliminar {
            get {
                return ResourceManager.GetString("eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Autorizador.
        /// </summary>
        public static string emailAutorizador {
            get {
                return ResourceManager.GetString("emailAutorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Validador.
        /// </summary>
        public static string emailValidador {
            get {
                return ResourceManager.GetString("emailValidador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa Facturadora.
        /// </summary>
        public static string empFacturadora {
            get {
                return ResourceManager.GetString("empFacturadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string empresa {
            get {
                return ResourceManager.GetString("empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa Facturadora.
        /// </summary>
        public static string empresaFacturadora {
            get {
                return ResourceManager.GetString("empresaFacturadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esquemas Pago.
        /// </summary>
        public static string esquema {
            get {
                return ResourceManager.GetString("esquema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esquemas.
        /// </summary>
        public static string Esquemas {
            get {
                return ResourceManager.GetString("Esquemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Civil.
        /// </summary>
        public static string estadoCivil {
            get {
                return ResourceManager.GetString("estadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string estatus {
            get {
                return ResourceManager.GetString("estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor.
        /// </summary>
        public static string factor {
            get {
                return ResourceManager.GetString("factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factores.
        /// </summary>
        public static string factores {
            get {
                return ResourceManager.GetString("factores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor de Integración.
        /// </summary>
        public static string factorIntegracion {
            get {
                return ResourceManager.GetString("factorIntegracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor Vacaciones.
        /// </summary>
        public static string factorVacaciones {
            get {
                return ResourceManager.GetString("factorVacaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar ingresar al SIAP.
        /// </summary>
        public static string failed_login {
            get {
                return ResourceManager.GetString("failed_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Alta.
        /// </summary>
        public static string fechaAlta {
            get {
                return ResourceManager.GetString("fechaAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Alta IMSS.
        /// </summary>
        public static string fechaAltaImss {
            get {
                return ResourceManager.GetString("fechaAltaImss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Baja.
        /// </summary>
        public static string fechaBaja {
            get {
                return ResourceManager.GetString("fechaBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Baja.
        /// </summary>
        public static string fechaFinal {
            get {
                return ResourceManager.GetString("fechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final Vigencia.
        /// </summary>
        public static string fechaFinalVigencia {
            get {
                return ResourceManager.GetString("fechaFinalVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Firma.
        /// </summary>
        public static string fechaFirma {
            get {
                return ResourceManager.GetString("fechaFirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio.
        /// </summary>
        public static string fechaInicio {
            get {
                return ResourceManager.GetString("fechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicial Vigencia.
        /// </summary>
        public static string fechaInicioVigencia {
            get {
                return ResourceManager.GetString("fechaInicioVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Modificación.
        /// </summary>
        public static string fechaModificacion {
            get {
                return ResourceManager.GetString("fechaModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento.
        /// </summary>
        public static string fechaNacimiento {
            get {
                return ResourceManager.GetString("fechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Registro.
        /// </summary>
        public static string fechaRegistro {
            get {
                return ResourceManager.GetString("fechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Solicitud.
        /// </summary>
        public static string fechaSolicitud {
            get {
                return ResourceManager.GetString("fechaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F. Fin Desc..
        /// </summary>
        public static string fFinDescuento {
            get {
                return ResourceManager.GetString("fFinDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.Ini.Desc..
        /// </summary>
        public static string fInicioDescuento {
            get {
                return ResourceManager.GetString("fInicioDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firmó.
        /// </summary>
        public static string firmo {
            get {
                return ResourceManager.GetString("firmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folio.
        /// </summary>
        public static string folioSolicitud {
            get {
                return ResourceManager.GetString("folioSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - SIAP Sistema de Administración de Personal IMSS.
        /// </summary>
        public static string footer_title {
            get {
                return ResourceManager.GetString("footer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Función.
        /// </summary>
        public static string funciones {
            get {
                return ResourceManager.GetString("funciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Giro.
        /// </summary>
        public static string giro {
            get {
                return ResourceManager.GetString("giro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string grupo {
            get {
                return ResourceManager.GetString("grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SIAP Web Site.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Homoclave.
        /// </summary>
        public static string homoClave {
            get {
                return ResourceManager.GetString("homoClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IFE Representante Legal.
        /// </summary>
        public static string ifeRepresentanteLegal {
            get {
                return ResourceManager.GetString("ifeRepresentanteLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador.
        /// </summary>
        public static string indicador {
            get {
                return ResourceManager.GetString("indicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA Flujo.
        /// </summary>
        public static string ivaFlujo {
            get {
                return ResourceManager.GetString("ivaFlujo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA IAS.
        /// </summary>
        public static string ivaIAS {
            get {
                return ResourceManager.GetString("ivaIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA Nómina.
        /// </summary>
        public static string ivaNomina {
            get {
                return ResourceManager.GetString("ivaNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Email Auxiliar.
        /// </summary>
        public static string listaEmailAux {
            get {
                return ResourceManager.GetString("listaEmailAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Validación Cliente.
        /// </summary>
        public static string lvalCliente {
            get {
                return ResourceManager.GetString("lvalCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string modificar {
            get {
                return ResourceManager.GetString("modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Módulo.
        /// </summary>
        public static string modulDes {
            get {
                return ResourceManager.GetString("modulDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo de la Baja.
        /// </summary>
        public static string motivoBaja {
            get {
                return ResourceManager.GetString("motivoBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        public static string municipio {
            get {
                return ResourceManager.GetString("municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Naturaleza.
        /// </summary>
        public static string naturaleza {
            get {
                return ResourceManager.GetString("naturaleza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Afiliacion.
        /// </summary>
        public static string noAfiliacion {
            get {
                return ResourceManager.GetString("noAfiliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Credito.
        /// </summary>
        public static string noCredito {
            get {
                return ResourceManager.GetString("noCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre(s).
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo.
        /// </summary>
        public static string nombreCompleto {
            get {
                return ResourceManager.GetString("nombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Corto.
        /// </summary>
        public static string nomCorto {
            get {
                return ResourceManager.GetString("nomCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N° Trabajadores.
        /// </summary>
        public static string noTrabajadores {
            get {
                return ResourceManager.GetString("noTrabajadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NSS.
        /// </summary>
        public static string nss {
            get {
                return ResourceManager.GetString("nss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Cuenta.
        /// </summary>
        public static string numeroCuenta {
            get {
                return ResourceManager.GetString("numeroCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string observaciones {
            get {
                return ResourceManager.GetString("observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupación.
        /// </summary>
        public static string ocupacion {
            get {
                return ResourceManager.GetString("ocupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro.
        /// </summary>
        public static string parametro {
            get {
                return ResourceManager.GetString("parametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro ID.
        /// </summary>
        public static string parametroId {
            get {
                return ResourceManager.GetString("parametroId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a parametros.
        /// </summary>
        public static string parametros {
            get {
                return ResourceManager.GetString("parametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patrón.
        /// </summary>
        public static string patron {
            get {
                return ResourceManager.GetString("patron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo.
        /// </summary>
        public static string periodo {
            get {
                return ResourceManager.GetString("periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plazas.
        /// </summary>
        public static string plaza {
            get {
                return ResourceManager.GetString("plaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plaza ID.
        /// </summary>
        public static string plazaId {
            get {
                return ResourceManager.GetString("plazaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poder Representante Legal.
        /// </summary>
        public static string poderRepresentanteLegal {
            get {
                return ResourceManager.GetString("poderRepresentanteLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje.
        /// </summary>
        public static string porcentaje {
            get {
                return ResourceManager.GetString("porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string posicion {
            get {
                return ResourceManager.GetString("posicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prima Vacacional.
        /// </summary>
        public static string primaVacacional {
            get {
                return ResourceManager.GetString("primaVacacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        public static string proyecto {
            get {
                return ResourceManager.GetString("proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Régimen Infonavit.
        /// </summary>
        public static string regInfonavit {
            get {
                return ResourceManager.GetString("regInfonavit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Patronal.
        /// </summary>
        public static string registroPatronal {
            get {
                return ResourceManager.GetString("registroPatronal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros.
        /// </summary>
        public static string registros {
            get {
                return ResourceManager.GetString("registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string regresar {
            get {
                return ResourceManager.GetString("regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Residencias.
        /// </summary>
        public static string residencia {
            get {
                return ResourceManager.GetString("residencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta Solicitud.
        /// </summary>
        public static string respuestaSolicitud {
            get {
                return ResourceManager.GetString("respuestaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retroceder.
        /// </summary>
        public static string retroceder {
            get {
                return ResourceManager.GetString("retroceder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RFC.
        /// </summary>
        public static string rfc {
            get {
                return ResourceManager.GetString("rfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string rol {
            get {
                return ResourceManager.GetString("rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salario Real.
        /// </summary>
        public static string salarioReal {
            get {
                return ResourceManager.GetString("salarioReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SD.
        /// </summary>
        public static string sd {
            get {
                return ResourceManager.GetString("sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SDI.
        /// </summary>
        public static string sdi {
            get {
                return ResourceManager.GetString("sdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio.
        /// </summary>
        public static string servicio {
            get {
                return ResourceManager.GetString("servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genero.
        /// </summary>
        public static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMDF.
        /// </summary>
        public static string smdf {
            get {
                return ResourceManager.GetString("smdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitó.
        /// </summary>
        public static string solicita {
            get {
                return ResourceManager.GetString("solicita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud.
        /// </summary>
        public static string solicitud {
            get {
                return ResourceManager.GetString("solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Baja.
        /// </summary>
        public static string solicitudBaja {
            get {
                return ResourceManager.GetString("solicitudBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Modificación.
        /// </summary>
        public static string SolicitudModificacion {
            get {
                return ResourceManager.GetString("SolicitudModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Acuse Masivo.
        /// </summary>
        public static string subirAcuseMax {
            get {
                return ResourceManager.GetString("subirAcuseMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Testigo.
        /// </summary>
        public static string testigo {
            get {
                return ResourceManager.GetString("testigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Contrato.
        /// </summary>
        public static string tipoContrato {
            get {
                return ResourceManager.GetString("tipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Personal.
        /// </summary>
        public static string tipoPersonal {
            get {
                return ResourceManager.GetString("tipoPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Servicio.
        /// </summary>
        public static string tipoServicio {
            get {
                return ResourceManager.GetString("tipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a Excel.
        /// </summary>
        public static string toExcel {
            get {
                return ResourceManager.GetString("toExcel", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a excelGeneral.
        /// </summary>
        public static string excelGeneral
        {
            get
            {
                return ResourceManager.GetString("excelGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a excelDetalle.
        /// </summary>
        public static string excelDetalle
        {
            get
            {
                return ResourceManager.GetString("excelDetalle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string ubicacion {
            get {
                return ResourceManager.GetString("ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Alta.
        /// </summary>
        public static string usuarioAlta {
            get {
                return ResourceManager.GetString("usuarioAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario ID.
        /// </summary>
        public static string usuarioID {
            get {
                return ResourceManager.GetString("usuarioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validador.
        /// </summary>
        public static string validador {
            get {
                return ResourceManager.GetString("validador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string valor {
            get {
                return ResourceManager.GetString("valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VSM.
        /// </summary>
        public static string vsm {
            get {
                return ResourceManager.GetString("vsm", resourceCulture);
            }
        }
    }
}
