//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
=======
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
>>>>>>> origin/2daEtapa
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUAMVC.Resources {
    using System;
    
    
    /// <summary>
<<<<<<< HEAD
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
=======
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
>>>>>>> origin/2daEtapa
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
=======
        ///   Returns the cached ResourceManager instance used by this class.
>>>>>>> origin/2daEtapa
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SUAMVC.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
=======
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
>>>>>>> origin/2daEtapa
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Acción.
=======
        ///   Looks up a localized string similar to Acción.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string accion {
            get {
                return ResourceManager.GetString("accion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Acreditados.
=======
        ///   Looks up a localized string similar to Acreditados.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string acreditados {
            get {
                return ResourceManager.GetString("acreditados", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Acta Constitutiva Empresa.
=======
        ///   Looks up a localized string similar to Acta Constitutiva Empresa.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string actaConstitutivaEmpresa {
            get {
                return ResourceManager.GetString("actaConstitutivaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Actividad Principal.
=======
        ///   Looks up a localized string similar to Actividad Principal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string actividadPrincipal {
            get {
                return ResourceManager.GetString("actividadPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Busqueda Avanzada.
=======
        ///   Looks up a localized string similar to Busqueda Avanzada.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string advanceSearch {
            get {
                return ResourceManager.GetString("advanceSearch", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Agregar.
=======
        ///   Looks up a localized string similar to Agregar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string agregar {
            get {
                return ResourceManager.GetString("agregar", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Aguinaldo.
=======
        ///   Looks up a localized string similar to Aguinaldo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string aguinaldo {
            get {
                return ResourceManager.GetString("aguinaldo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Años Trabajados.
=======
        ///   Looks up a localized string similar to Años Trabajados.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string anosTrabajados {
            get {
                return ResourceManager.GetString("anosTrabajados", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Apellido Materno.
=======
        ///   Looks up a localized string similar to Apellido Materno.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string apellidoMaterno {
            get {
                return ResourceManager.GetString("apellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Apellido Paterno.
=======
        ///   Looks up a localized string similar to Apellido Paterno.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string apellidoPaterno {
            get {
                return ResourceManager.GetString("apellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Archivo 1.
=======
        ///   Looks up a localized string similar to Archivo 1.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string archivo1 {
            get {
                return ResourceManager.GetString("archivo1", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Archivo 2.
=======
        ///   Looks up a localized string similar to Archivo 2.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string archivo2 {
            get {
                return ResourceManager.GetString("archivo2", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Archivo 3.
=======
        ///   Looks up a localized string similar to Archivo 3.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string archivo3 {
            get {
                return ResourceManager.GetString("archivo3", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Autorizador.
=======
        ///   Looks up a localized string similar to Autorizador.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string autorizador {
            get {
                return ResourceManager.GetString("autorizador", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Avanzar.
=======
        ///   Looks up a localized string similar to Avanzar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string avanzar {
            get {
                return ResourceManager.GetString("avanzar", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Aviso Incapacidad.
=======
        ///   Looks up a localized string similar to Aviso Incapacidad.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string avisoInc {
            get {
                return ResourceManager.GetString("avisoInc", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Aviso Ret..
=======
        ///   Looks up a localized string similar to Aviso Ret..
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string avisoRet {
            get {
                return ResourceManager.GetString("avisoRet", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Banco.
=======
        ///   Looks up a localized string similar to Banco.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string banco {
            get {
                return ResourceManager.GetString("banco", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Bancos.
=======
        ///   Looks up a localized string similar to Bancos.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string bancos {
            get {
                return ResourceManager.GetString("bancos", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Borrar.
=======
        ///   Looks up a localized string similar to Borrar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Cancelar.
=======
        ///   Looks up a localized string similar to Cancelar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string bt_cancel {
            get {
                return ResourceManager.GetString("bt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Salir.
=======
        ///   Looks up a localized string similar to Salir.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string bt_exit {
            get {
                return ResourceManager.GetString("bt_exit", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Ingresar.
=======
        ///   Looks up a localized string similar to Ingresar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string bt_login {
            get {
                return ResourceManager.GetString("bt_login", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Registrarse.
=======
        ///   Looks up a localized string similar to Registrarse.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string bt_register {
            get {
                return ResourceManager.GetString("bt_register", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Catálogo de Datos Adicionales Cliente.
=======
        ///   Looks up a localized string similar to Catálogo de Datos Adicionales Cliente.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string catDatAdCliente {
            get {
                return ResourceManager.GetString("catDatAdCliente", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Catálogo de.
=======
        ///   Looks up a localized string similar to Catálogo de.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string catde {
            get {
                return ResourceManager.GetString("catde", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Categoría.
=======
        ///   Looks up a localized string similar to Categoría.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Clave Grupo.
=======
        ///   Looks up a localized string similar to Clave Grupo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string claGrupo {
            get {
                return ResourceManager.GetString("claGrupo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Clave Cliente.
=======
        ///   Looks up a localized string similar to Clave Cliente.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string claveCliente {
            get {
                return ResourceManager.GetString("claveCliente", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Clave SUA.
=======
        ///   Looks up a localized string similar to Clave SUA.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string claveSua {
            get {
                return ResourceManager.GetString("claveSua", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Clave Usuario.
=======
        ///   Looks up a localized string similar to Clave Usuario.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string claveUsuario {
            get {
                return ResourceManager.GetString("claveUsuario", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Clave Cliente.
        /// </summary>
        public static string cleveCliente {
            get {
                return ResourceManager.GetString("cleveCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
=======
        ///   Looks up a localized string similar to Cliente.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string cliente {
            get {
                return ResourceManager.GetString("cliente", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Cliente ID.
=======
        ///   Looks up a localized string similar to Cliente ID.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string clienteId {
            get {
                return ResourceManager.GetString("clienteId", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a SIAP.
=======
        ///   Looks up a localized string similar to SIAP.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a IMSS 3.0.
=======
        ///   Looks up a localized string similar to IMSS 3.0.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string company_subtitle {
            get {
                return ResourceManager.GetString("company_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Comprobante de Domicilio.
=======
        ///   Looks up a localized string similar to Comprobante de Domicilio.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string comprobanteDomicilio {
            get {
                return ResourceManager.GetString("comprobanteDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Estatus Solicitud.
=======
        ///   Looks up a localized string similar to Estatus Solicitud.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string concepDescripcion {
            get {
                return ResourceManager.GetString("concepDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Estatus Nom..
=======
        ///   Looks up a localized string similar to Estatus Nom..
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string concepDescripcion1 {
            get {
                return ResourceManager.GetString("concepDescripcion1", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Estatus Jurídico.
=======
        ///   Looks up a localized string similar to Estatus Jurídico.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string concepDescripcion2 {
            get {
                return ResourceManager.GetString("concepDescripcion2", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Estatus Afil..
=======
        ///   Looks up a localized string similar to Estatus Afil..
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string concepDescripcion3 {
            get {
                return ResourceManager.GetString("concepDescripcion3", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Estatus Tarj..
=======
        ///   Looks up a localized string similar to Estatus Tarj..
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string concepDescripcion4 {
            get {
                return ResourceManager.GetString("concepDescripcion4", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Concepto de Facturación.
=======
        ///   Looks up a localized string similar to Concepto de Facturación.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string concepFacturacion {
            get {
                return ResourceManager.GetString("concepFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Concepto.
=======
        ///   Looks up a localized string similar to Concepto.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string concepto {
            get {
                return ResourceManager.GetString("concepto", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Consultar.
=======
        ///   Looks up a localized string similar to Consultar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string consulta {
            get {
                return ResourceManager.GetString("consulta", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        public static string consultar {
            get {
                return ResourceManager.GetString("consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
=======
        ///   Looks up a localized string similar to Contacto.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Contrato Cliente.
=======
        ///   Looks up a localized string similar to Contrato Cliente.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string contCliente {
            get {
                return ResourceManager.GetString("contCliente", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Contraseña.
=======
        ///   Looks up a localized string similar to Contraseña.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string contrasena {
            get {
                return ResourceManager.GetString("contrasena", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Contrato Cliente.
=======
        ///   Looks up a localized string similar to Contrato Cliente.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string contratosClientes {
            get {
                return ResourceManager.GetString("contratosClientes", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Controlador.
=======
        ///   Looks up a localized string similar to Controlador.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string controlador {
            get {
                return ResourceManager.GetString("controlador", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Costo Social.
=======
        ///   Looks up a localized string similar to Costo Social.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string costSocial {
            get {
                return ResourceManager.GetString("costSocial", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Criterio.
=======
        ///   Looks up a localized string similar to Criterio.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string criterio {
            get {
                return ResourceManager.GetString("criterio", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Cuenta Bancaria.
=======
        ///   Looks up a localized string similar to Cuenta Bancaria.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string cuentaBancaria {
            get {
                return ResourceManager.GetString("cuentaBancaria", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Cuenta Clave.
=======
        ///   Looks up a localized string similar to Cuenta Clave.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string cuentaClabe {
            get {
                return ResourceManager.GetString("cuentaClabe", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Cuota Fija.
=======
        ///   Looks up a localized string similar to Cuota Fija.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string cuotaFija {
            get {
                return ResourceManager.GetString("cuotaFija", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a CURP.
=======
        ///   Looks up a localized string similar to CURP.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string curp {
            get {
                return ResourceManager.GetString("curp", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Clave Corta.
=======
        ///   Looks up a localized string similar to Clave Corta.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string cveCorta {
            get {
                return ResourceManager.GetString("cveCorta", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Datos Adicionales Cliente.
=======
        ///   Looks up a localized string similar to Datos Adicionales Cliente.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string datAdiCliente {
            get {
                return ResourceManager.GetString("datAdiCliente", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Departamento.
=======
        ///   Looks up a localized string similar to Departamento.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string dep {
            get {
                return ResourceManager.GetString("dep", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Departamento.
=======
        ///   Looks up a localized string similar to Departamento.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string departamento {
            get {
                return ResourceManager.GetString("departamento", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Desc. Bimestral.
=======
        ///   Looks up a localized string similar to Desc. Bimestral.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string descBimestral {
            get {
                return ResourceManager.GetString("descBimestral", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Desc. Catorcenal.
=======
        ///   Looks up a localized string similar to Desc. Catorcenal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string descCatorcenal {
            get {
                return ResourceManager.GetString("descCatorcenal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Desc. Diario.
=======
        ///   Looks up a localized string similar to Desc. Diario.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string descDiario {
            get {
                return ResourceManager.GetString("descDiario", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Desc. Mensual.
=======
        ///   Looks up a localized string similar to Desc. Mensual.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string descMensual {
            get {
                return ResourceManager.GetString("descMensual", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Descripción Corta.
=======
        ///   Looks up a localized string similar to Descripción Corta.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string desCorta {
            get {
                return ResourceManager.GetString("desCorta", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Descripcion País.
=======
        ///   Looks up a localized string similar to Descripcion País.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string descPais {
            get {
                return ResourceManager.GetString("descPais", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Desc. Quincenal.
=======
        ///   Looks up a localized string similar to Desc. Quincenal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string descQuincenal {
            get {
                return ResourceManager.GetString("descQuincenal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Descripción.
=======
        ///   Looks up a localized string similar to Descripción.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Desc. Semanal.
=======
        ///   Looks up a localized string similar to Desc. Semanal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string descSemanal {
            get {
                return ResourceManager.GetString("descSemanal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Desc. Veintiochonal.
=======
        ///   Looks up a localized string similar to Desc. Veintiochonal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string descVeintiocho {
            get {
                return ResourceManager.GetString("descVeintiocho", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Descripción Larga.
=======
        ///   Looks up a localized string similar to Descripción Larga.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string desLarga {
            get {
                return ResourceManager.GetString("desLarga", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Proyecto.
=======
        ///   Looks up a localized string similar to Proyecto.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string desProyecto {
            get {
                return ResourceManager.GetString("desProyecto", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Detalle.
=======
        ///   Looks up a localized string similar to Detalle.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string detalle {
            get {
                return ResourceManager.GetString("detalle", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Detalles de.
=======
        ///   Looks up a localized string similar to Detalles de.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string detallesDe {
            get {
                return ResourceManager.GetString("detallesDe", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Días al Año.
=======
        ///   Looks up a localized string similar to Días al Año.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string diasAno {
            get {
                return ResourceManager.GetString("diasAno", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Días Año Aguinaldo.
=======
        ///   Looks up a localized string similar to Días Año Aguinaldo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string diasAnoAguinaldo {
            get {
                return ResourceManager.GetString("diasAnoAguinaldo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Días de Vacaciones.
=======
        ///   Looks up a localized string similar to Días de Vacaciones.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string diasVacaciones {
            get {
                return ResourceManager.GetString("diasVacaciones", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Dirección Fiscal.
=======
        ///   Looks up a localized string similar to Dirección Fiscal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string direccionFiscal {
            get {
                return ResourceManager.GetString("direccionFiscal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Dirección de Oficina.
=======
        ///   Looks up a localized string similar to Dirección de Oficina.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string direccionOficina {
            get {
                return ResourceManager.GetString("direccionOficina", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Direección Fiscal.
=======
        ///   Looks up a localized string similar to Direección Fiscal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string direcFiscal {
            get {
                return ResourceManager.GetString("direcFiscal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Editar.
=======
        ///   Looks up a localized string similar to Editar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Ejecutivo.
=======
        ///   Looks up a localized string similar to Ejecutivo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string ejecutivo {
            get {
                return ResourceManager.GetString("ejecutivo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Ejecutivo Contador.
=======
        ///   Looks up a localized string similar to Ejecutivo Contador.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string ejecutivoContador {
            get {
                return ResourceManager.GetString("ejecutivoContador", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Ejercicio.
=======
        ///   Looks up a localized string similar to Ejercicio.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string ejercicio {
            get {
                return ResourceManager.GetString("ejercicio", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a .
=======
        ///   Looks up a localized string similar to .
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string eliminar {
            get {
                return ResourceManager.GetString("eliminar", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a E mail.
=======
        ///   Looks up a localized string similar to E mail.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Email Autorizador.
=======
        ///   Looks up a localized string similar to Email Autorizador.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string emailAutorizador {
            get {
                return ResourceManager.GetString("emailAutorizador", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Email Validador.
=======
        ///   Looks up a localized string similar to Email Validador.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string emailValidador {
            get {
                return ResourceManager.GetString("emailValidador", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Empresa Facturadora.
=======
        ///   Looks up a localized string similar to Empresa Facturadora.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string empFacturadora {
            get {
                return ResourceManager.GetString("empFacturadora", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Empresa.
=======
        ///   Looks up a localized string similar to Empresa.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string empresa {
            get {
                return ResourceManager.GetString("empresa", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Empresa Facturadora.
=======
        ///   Looks up a localized string similar to Empresa Facturadora.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string empresaFacturadora {
            get {
                return ResourceManager.GetString("empresaFacturadora", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Esquemas Pago.
=======
        ///   Looks up a localized string similar to Esquemas Pago.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string esquema {
            get {
                return ResourceManager.GetString("esquema", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Esquemas.
=======
        ///   Looks up a localized string similar to Esquemas.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string Esquemas {
            get {
                return ResourceManager.GetString("Esquemas", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Estado.
=======
        ///   Looks up a localized string similar to Estado.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Estado Civil.
=======
        ///   Looks up a localized string similar to Estado Civil.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string estadoCivil {
            get {
                return ResourceManager.GetString("estadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Estatus.
=======
        ///   Looks up a localized string similar to Estatus.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string estatus {
            get {
                return ResourceManager.GetString("estatus", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Factor.
=======
        ///   Looks up a localized string similar to Factor.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string factor {
            get {
                return ResourceManager.GetString("factor", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Factores.
=======
        ///   Looks up a localized string similar to Factores.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string factores {
            get {
                return ResourceManager.GetString("factores", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Factor de Integración.
=======
        ///   Looks up a localized string similar to Factor de Integración.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string factorIntegracion {
            get {
                return ResourceManager.GetString("factorIntegracion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Factor Vacaciones.
=======
        ///   Looks up a localized string similar to Factor Vacaciones.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string factorVacaciones {
            get {
                return ResourceManager.GetString("factorVacaciones", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Error al intentar ingresar al SIAP.
=======
        ///   Looks up a localized string similar to Error al intentar ingresar al SIAP.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string failed_login {
            get {
                return ResourceManager.GetString("failed_login", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha Alta.
=======
        ///   Looks up a localized string similar to Fecha Alta.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaAlta {
            get {
                return ResourceManager.GetString("fechaAlta", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha Alta IMSS.
=======
        ///   Looks up a localized string similar to Fecha Alta IMSS.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaAltaImss {
            get {
                return ResourceManager.GetString("fechaAltaImss", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha Baja.
=======
        ///   Looks up a localized string similar to Fecha Baja.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaBaja {
            get {
                return ResourceManager.GetString("fechaBaja", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha Baja.
=======
        ///   Looks up a localized string similar to Fecha Baja.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaFinal {
            get {
                return ResourceManager.GetString("fechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha Final Vigencia.
=======
        ///   Looks up a localized string similar to Fecha Final Vigencia.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaFinalVigencia {
            get {
                return ResourceManager.GetString("fechaFinalVigencia", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha Firma.
=======
        ///   Looks up a localized string similar to Fecha Firma.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaFirma {
            get {
                return ResourceManager.GetString("fechaFirma", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha de Inicio.
=======
        ///   Looks up a localized string similar to Fecha de Inicio.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaInicio {
            get {
                return ResourceManager.GetString("fechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha Inicial Vigencia.
=======
        ///   Looks up a localized string similar to Fecha Inicial Vigencia.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaInicioVigencia {
            get {
                return ResourceManager.GetString("fechaInicioVigencia", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha de Modificación.
=======
        ///   Looks up a localized string similar to Fecha de Modificación.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaModificacion {
            get {
                return ResourceManager.GetString("fechaModificacion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha de Nacimiento.
=======
        ///   Looks up a localized string similar to Fecha de Nacimiento.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaNacimiento {
            get {
                return ResourceManager.GetString("fechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha Registro.
=======
        ///   Looks up a localized string similar to Fecha Registro.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaRegistro {
            get {
                return ResourceManager.GetString("fechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Fecha de Solicitud.
=======
        ///   Looks up a localized string similar to Fecha de Solicitud.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fechaSolicitud {
            get {
                return ResourceManager.GetString("fechaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a F. Fin Desc..
=======
        ///   Looks up a localized string similar to F. Fin Desc..
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fFinDescuento {
            get {
                return ResourceManager.GetString("fFinDescuento", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a F.Ini.Desc..
=======
        ///   Looks up a localized string similar to F.Ini.Desc..
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string fInicioDescuento {
            get {
                return ResourceManager.GetString("fInicioDescuento", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Firmó.
=======
        ///   Looks up a localized string similar to Firmó.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string firmo {
            get {
                return ResourceManager.GetString("firmo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Folio.
=======
        ///   Looks up a localized string similar to Folio.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string folioSolicitud {
            get {
                return ResourceManager.GetString("folioSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a - SIAP Sistema de Administración de Personal IMSS.
=======
        ///   Looks up a localized string similar to - SIAP Sistema de Administración de Personal IMSS.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string footer_title {
            get {
                return ResourceManager.GetString("footer_title", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Función.
=======
        ///   Looks up a localized string similar to Función.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string funciones {
            get {
                return ResourceManager.GetString("funciones", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Giro.
=======
        ///   Looks up a localized string similar to Giro.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string giro {
            get {
                return ResourceManager.GetString("giro", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Grupo.
=======
        ///   Looks up a localized string similar to Grupo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string grupo {
            get {
                return ResourceManager.GetString("grupo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Guardar.
=======
        ///   Looks up a localized string similar to Guardar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a SIAP Web Site.
=======
        ///   Looks up a localized string similar to SIAP Web Site.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Homoclave.
=======
        ///   Looks up a localized string similar to Homoclave.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string homoClave {
            get {
                return ResourceManager.GetString("homoClave", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a IFE Representante Legal.
=======
        ///   Looks up a localized string similar to IFE Representante Legal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string ifeRepresentanteLegal {
            get {
                return ResourceManager.GetString("ifeRepresentanteLegal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Indicador.
=======
        ///   Looks up a localized string similar to Indicador.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string indicador {
            get {
                return ResourceManager.GetString("indicador", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a IVA Flujo.
=======
        ///   Looks up a localized string similar to IVA Flujo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string ivaFlujo {
            get {
                return ResourceManager.GetString("ivaFlujo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a IVA IAS.
=======
        ///   Looks up a localized string similar to IVA IAS.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string ivaIAS {
            get {
                return ResourceManager.GetString("ivaIAS", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a IVA Nómina.
=======
        ///   Looks up a localized string similar to IVA Nómina.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string ivaNomina {
            get {
                return ResourceManager.GetString("ivaNomina", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Lista Email Auxiliar.
=======
        ///   Looks up a localized string similar to Lista Email Auxiliar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string listaEmailAux {
            get {
                return ResourceManager.GetString("listaEmailAux", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Lista de Validación Cliente.
=======
        ///   Looks up a localized string similar to Lista de Validación Cliente.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string lvalCliente {
            get {
                return ResourceManager.GetString("lvalCliente", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Modificar.
=======
        ///   Looks up a localized string similar to Modificar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string modificar {
            get {
                return ResourceManager.GetString("modificar", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Módulo.
=======
        ///   Looks up a localized string similar to Módulo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string modulDes {
            get {
                return ResourceManager.GetString("modulDes", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Motivo de la Baja.
=======
        ///   Looks up a localized string similar to Motivo de la Baja.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string motivoBaja {
            get {
                return ResourceManager.GetString("motivoBaja", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Municipio.
=======
        ///   Looks up a localized string similar to Municipio.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string municipio {
            get {
                return ResourceManager.GetString("municipio", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Naturaleza.
=======
        ///   Looks up a localized string similar to Naturaleza.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string naturaleza {
            get {
                return ResourceManager.GetString("naturaleza", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a No. Afiliacion.
=======
        ///   Looks up a localized string similar to No. Afiliacion.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string noAfiliacion {
            get {
                return ResourceManager.GetString("noAfiliacion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a No. Credito.
=======
        ///   Looks up a localized string similar to No. Credito.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string noCredito {
            get {
                return ResourceManager.GetString("noCredito", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Nombre(s).
=======
        ///   Looks up a localized string similar to Nombre(s).
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Nombre Completo.
=======
        ///   Looks up a localized string similar to Nombre Completo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string nombreCompleto {
            get {
                return ResourceManager.GetString("nombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Nombre Corto.
=======
        ///   Looks up a localized string similar to Nombre Corto.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string nomCorto {
            get {
                return ResourceManager.GetString("nomCorto", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a N° Trabajadores.
=======
        ///   Looks up a localized string similar to N° Trabajadores.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string noTrabajadores {
            get {
                return ResourceManager.GetString("noTrabajadores", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a NSS.
=======
        ///   Looks up a localized string similar to NSS.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string nss {
            get {
                return ResourceManager.GetString("nss", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Número de Cuenta.
=======
        ///   Looks up a localized string similar to Número de Cuenta.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string numeroCuenta {
            get {
                return ResourceManager.GetString("numeroCuenta", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Observaciones.
=======
        ///   Looks up a localized string similar to Observaciones.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string observaciones {
            get {
                return ResourceManager.GetString("observaciones", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Ocupación.
=======
        ///   Looks up a localized string similar to Ocupación.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string ocupacion {
            get {
                return ResourceManager.GetString("ocupacion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a País.
=======
        ///   Looks up a localized string similar to País.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Parámetro.
=======
        ///   Looks up a localized string similar to Parámetro.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string parametro {
            get {
                return ResourceManager.GetString("parametro", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Parámetro ID.
=======
        ///   Looks up a localized string similar to Parámetro ID.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string parametroId {
            get {
                return ResourceManager.GetString("parametroId", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a parametros.
=======
        ///   Looks up a localized string similar to parametros.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string parametros {
            get {
                return ResourceManager.GetString("parametros", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Patrón.
=======
        ///   Looks up a localized string similar to Patrón.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string patron {
            get {
                return ResourceManager.GetString("patron", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Periodo.
=======
        ///   Looks up a localized string similar to Periodo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string periodo {
            get {
                return ResourceManager.GetString("periodo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Plazas.
=======
        ///   Looks up a localized string similar to Plazas.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string plaza {
            get {
                return ResourceManager.GetString("plaza", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Plaza ID.
=======
        ///   Looks up a localized string similar to Plaza ID.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string plazaId {
            get {
                return ResourceManager.GetString("plazaId", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Poder Representante Legal.
=======
        ///   Looks up a localized string similar to Poder Representante Legal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string poderRepresentanteLegal {
            get {
                return ResourceManager.GetString("poderRepresentanteLegal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Porcentaje.
=======
        ///   Looks up a localized string similar to Porcentaje.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string porcentaje {
            get {
                return ResourceManager.GetString("porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Posición.
=======
        ///   Looks up a localized string similar to Posición.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string posicion {
            get {
                return ResourceManager.GetString("posicion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Prima Vacacional.
=======
        ///   Looks up a localized string similar to Prima Vacacional.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string primaVacacional {
            get {
                return ResourceManager.GetString("primaVacacional", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Proyecto.
=======
        ///   Looks up a localized string similar to Proyecto.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string proyecto {
            get {
                return ResourceManager.GetString("proyecto", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Régimen Infonavit.
=======
        ///   Looks up a localized string similar to Régimen Infonavit.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string regInfonavit {
            get {
                return ResourceManager.GetString("regInfonavit", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Registro Patronal.
=======
        ///   Looks up a localized string similar to Registro Patronal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string registroPatronal {
            get {
                return ResourceManager.GetString("registroPatronal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Registros.
=======
        ///   Looks up a localized string similar to Registros.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string registros {
            get {
                return ResourceManager.GetString("registros", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Regresar.
=======
        ///   Looks up a localized string similar to Regresar.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string regresar {
            get {
                return ResourceManager.GetString("regresar", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Residencias.
=======
        ///   Looks up a localized string similar to Residencias.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string residencia {
            get {
                return ResourceManager.GetString("residencia", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Respuesta Solicitud.
=======
        ///   Looks up a localized string similar to Respuesta Solicitud.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string respuestaSolicitud {
            get {
                return ResourceManager.GetString("respuestaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Retroceder.
=======
        ///   Looks up a localized string similar to Retroceder.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string retroceder {
            get {
                return ResourceManager.GetString("retroceder", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a RFC.
=======
        ///   Looks up a localized string similar to RFC.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string rfc {
            get {
                return ResourceManager.GetString("rfc", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Rol.
=======
        ///   Looks up a localized string similar to Rol.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string rol {
            get {
                return ResourceManager.GetString("rol", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Salario Real.
=======
        ///   Looks up a localized string similar to Salario Real.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string salarioReal {
            get {
                return ResourceManager.GetString("salarioReal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a SD.
=======
        ///   Looks up a localized string similar to SD.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string sd {
            get {
                return ResourceManager.GetString("sd", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a SDI.
=======
        ///   Looks up a localized string similar to SDI.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string sdi {
            get {
                return ResourceManager.GetString("sdi", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Servicio.
=======
        ///   Looks up a localized string similar to Servicio.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string servicio {
            get {
                return ResourceManager.GetString("servicio", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Genero.
=======
        ///   Looks up a localized string similar to Genero.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a SMDF.
=======
        ///   Looks up a localized string similar to SMDF.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string smdf {
            get {
                return ResourceManager.GetString("smdf", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Solicitó.
=======
        ///   Looks up a localized string similar to Solicitó.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string solicita {
            get {
                return ResourceManager.GetString("solicita", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Solicitud.
=======
        ///   Looks up a localized string similar to Solicitud.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string solicitud {
            get {
                return ResourceManager.GetString("solicitud", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Solicitud Baja.
=======
        ///   Looks up a localized string similar to Solicitud Baja.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string solicitudBaja {
            get {
                return ResourceManager.GetString("solicitudBaja", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Solicitud Modificación.
=======
        ///   Looks up a localized string similar to Solicitud Modificación.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string SolicitudModificacion {
            get {
                return ResourceManager.GetString("SolicitudModificacion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Subir Acuse Masivo.
=======
        ///   Looks up a localized string similar to Subir Acuse Masivo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string subirAcuseMax {
            get {
                return ResourceManager.GetString("subirAcuseMax", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Teléfono.
=======
        ///   Looks up a localized string similar to Teléfono.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Testigo.
=======
        ///   Looks up a localized string similar to Testigo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string testigo {
            get {
                return ResourceManager.GetString("testigo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Tipo.
=======
        ///   Looks up a localized string similar to Tipo.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Tipo de Contrato.
=======
        ///   Looks up a localized string similar to Tipo de Contrato.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string tipoContrato {
            get {
                return ResourceManager.GetString("tipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Tipo de Personal.
=======
        ///   Looks up a localized string similar to Tipo de Personal.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string tipoPersonal {
            get {
                return ResourceManager.GetString("tipoPersonal", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Tipo de Servicio.
=======
        ///   Looks up a localized string similar to Tipo de Servicio.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string tipoServicio {
            get {
                return ResourceManager.GetString("tipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Exportar a Excel.
=======
        ///   Looks up a localized string similar to Exportar a Excel.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string toExcel {
            get {
                return ResourceManager.GetString("toExcel", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Ubicación.
=======
        ///   Looks up a localized string similar to Ubicación.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string ubicacion {
            get {
                return ResourceManager.GetString("ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Usuario Alta.
=======
        ///   Looks up a localized string similar to Usuario Alta.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string usuarioAlta {
            get {
                return ResourceManager.GetString("usuarioAlta", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Usuario ID.
=======
        ///   Looks up a localized string similar to Usuario ID.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string usuarioID {
            get {
                return ResourceManager.GetString("usuarioID", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Validador.
=======
        ///   Looks up a localized string similar to Validador.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string validador {
            get {
                return ResourceManager.GetString("validador", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Valor.
=======
        ///   Looks up a localized string similar to Valor.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string valor {
            get {
                return ResourceManager.GetString("valor", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a VSM.
=======
        ///   Looks up a localized string similar to VSM.
>>>>>>> origin/2daEtapa
        /// </summary>
        public static string vsm {
            get {
                return ResourceManager.GetString("vsm", resourceCulture);
            }
        }
    }
}
