//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUAMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SUAMVC.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string accion {
            get {
                return ResourceManager.GetString("accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acreditados.
        /// </summary>
        public static string acreditados {
            get {
                return ResourceManager.GetString("acreditados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acta Constitutiva Empresa.
        /// </summary>
        public static string actaConstitutivaEmpresa {
            get {
                return ResourceManager.GetString("actaConstitutivaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Principal.
        /// </summary>
        public static string actividadPrincipal {
            get {
                return ResourceManager.GetString("actividadPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busqueda Avanzada.
        /// </summary>
        public static string advanceSearch {
            get {
                return ResourceManager.GetString("advanceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string agregar {
            get {
                return ResourceManager.GetString("agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguinaldo.
        /// </summary>
        public static string aguinaldo {
            get {
                return ResourceManager.GetString("aguinaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Años Trabajados.
        /// </summary>
        public static string anosTrabajados {
            get {
                return ResourceManager.GetString("anosTrabajados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Materno.
        /// </summary>
        public static string apellidoMaterno {
            get {
                return ResourceManager.GetString("apellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Paterno.
        /// </summary>
        public static string apellidoPaterno {
            get {
                return ResourceManager.GetString("apellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo 1.
        /// </summary>
        public static string archivo1 {
            get {
                return ResourceManager.GetString("archivo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo 2.
        /// </summary>
        public static string archivo2 {
            get {
                return ResourceManager.GetString("archivo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo 3.
        /// </summary>
        public static string archivo3 {
            get {
                return ResourceManager.GetString("archivo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizador.
        /// </summary>
        public static string autorizador {
            get {
                return ResourceManager.GetString("autorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanzar.
        /// </summary>
        public static string avanzar {
            get {
                return ResourceManager.GetString("avanzar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso Incapacidad.
        /// </summary>
        public static string avisoInc {
            get {
                return ResourceManager.GetString("avisoInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso Ret..
        /// </summary>
        public static string avisoRet {
            get {
                return ResourceManager.GetString("avisoRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco.
        /// </summary>
        public static string banco {
            get {
                return ResourceManager.GetString("banco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos.
        /// </summary>
        public static string bancos {
            get {
                return ResourceManager.GetString("bancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string bt_cancel {
            get {
                return ResourceManager.GetString("bt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string bt_exit {
            get {
                return ResourceManager.GetString("bt_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string bt_login {
            get {
                return ResourceManager.GetString("bt_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string bt_register {
            get {
                return ResourceManager.GetString("bt_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Datos Adicionales Cliente.
        /// </summary>
        public static string catDatAdCliente {
            get {
                return ResourceManager.GetString("catDatAdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de.
        /// </summary>
        public static string catde {
            get {
                return ResourceManager.GetString("catde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave Grupo.
        /// </summary>
        public static string claGrupo {
            get {
                return ResourceManager.GetString("claGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave Cliente.
        /// </summary>
        public static string claveCliente {
            get {
                return ResourceManager.GetString("claveCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave SUA.
        /// </summary>
        public static string claveSua {
            get {
                return ResourceManager.GetString("claveSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave Usuario.
        /// </summary>
        public static string claveUsuario {
            get {
                return ResourceManager.GetString("claveUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string cliente {
            get {
                return ResourceManager.GetString("cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente ID.
        /// </summary>
        public static string clienteId {
            get {
                return ResourceManager.GetString("clienteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIAP.
        /// </summary>
        public static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMSS 3.0.
        /// </summary>
        public static string company_subtitle {
            get {
                return ResourceManager.GetString("company_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobante de Domicilio.
        /// </summary>
        public static string comprobanteDomicilio {
            get {
                return ResourceManager.GetString("comprobanteDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus Solicitud.
        /// </summary>
        public static string concepDescripcion {
            get {
                return ResourceManager.GetString("concepDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus Nom..
        /// </summary>
        public static string concepDescripcion1 {
            get {
                return ResourceManager.GetString("concepDescripcion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus Jurídico.
        /// </summary>
        public static string concepDescripcion2 {
            get {
                return ResourceManager.GetString("concepDescripcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus Afil..
        /// </summary>
        public static string concepDescripcion3 {
            get {
                return ResourceManager.GetString("concepDescripcion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus Tarj..
        /// </summary>
        public static string concepDescripcion4 {
            get {
                return ResourceManager.GetString("concepDescripcion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto de Facturación.
        /// </summary>
        public static string concepFacturacion {
            get {
                return ResourceManager.GetString("concepFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto.
        /// </summary>
        public static string concepto {
            get {
                return ResourceManager.GetString("concepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string consulta {
            get {
                return ResourceManager.GetString("consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato Cliente.
        /// </summary>
        public static string contCliente {
            get {
                return ResourceManager.GetString("contCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string contrasena {
            get {
                return ResourceManager.GetString("contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        public static string contrato {
            get {
                return ResourceManager.GetString("contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato Cliente.
        /// </summary>
        public static string contratosClientes {
            get {
                return ResourceManager.GetString("contratosClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlador.
        /// </summary>
        public static string controlador {
            get {
                return ResourceManager.GetString("controlador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo Social.
        /// </summary>
        public static string costSocial {
            get {
                return ResourceManager.GetString("costSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterio.
        /// </summary>
        public static string criterio {
            get {
                return ResourceManager.GetString("criterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta Bancaria.
        /// </summary>
        public static string cuentaBancaria {
            get {
                return ResourceManager.GetString("cuentaBancaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta Clave.
        /// </summary>
        public static string cuentaClabe {
            get {
                return ResourceManager.GetString("cuentaClabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuota Fija.
        /// </summary>
        public static string cuotaFija {
            get {
                return ResourceManager.GetString("cuotaFija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURP.
        /// </summary>
        public static string curp {
            get {
                return ResourceManager.GetString("curp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave Corta.
        /// </summary>
        public static string cveCorta {
            get {
                return ResourceManager.GetString("cveCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Adicionales Cliente.
        /// </summary>
        public static string datAdiCliente {
            get {
                return ResourceManager.GetString("datAdiCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        public static string dep {
            get {
                return ResourceManager.GetString("dep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        public static string departamento {
            get {
                return ResourceManager.GetString("departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc. Bimestral.
        /// </summary>
        public static string descBimestral {
            get {
                return ResourceManager.GetString("descBimestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc. Catorcenal.
        /// </summary>
        public static string descCatorcenal {
            get {
                return ResourceManager.GetString("descCatorcenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc. Diario.
        /// </summary>
        public static string descDiario {
            get {
                return ResourceManager.GetString("descDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc. Mensual.
        /// </summary>
        public static string descMensual {
            get {
                return ResourceManager.GetString("descMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Corta.
        /// </summary>
        public static string desCorta {
            get {
                return ResourceManager.GetString("desCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion País.
        /// </summary>
        public static string descPais {
            get {
                return ResourceManager.GetString("descPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc. Quincenal.
        /// </summary>
        public static string descQuincenal {
            get {
                return ResourceManager.GetString("descQuincenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc. Semanal.
        /// </summary>
        public static string descSemanal {
            get {
                return ResourceManager.GetString("descSemanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc. Veintiochonal.
        /// </summary>
        public static string descVeintiocho {
            get {
                return ResourceManager.GetString("descVeintiocho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Larga.
        /// </summary>
        public static string desLarga {
            get {
                return ResourceManager.GetString("desLarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto.
        /// </summary>
        public static string desProyecto {
            get {
                return ResourceManager.GetString("desProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string detalle {
            get {
                return ResourceManager.GetString("detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de.
        /// </summary>
        public static string detallesDe {
            get {
                return ResourceManager.GetString("detallesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días al Año.
        /// </summary>
        public static string diasAno {
            get {
                return ResourceManager.GetString("diasAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días Año Aguinaldo.
        /// </summary>
        public static string diasAnoAguinaldo {
            get {
                return ResourceManager.GetString("diasAnoAguinaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días de Vacaciones.
        /// </summary>
        public static string diasVacaciones {
            get {
                return ResourceManager.GetString("diasVacaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección Fiscal.
        /// </summary>
        public static string direccionFiscal {
            get {
                return ResourceManager.GetString("direccionFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de Oficina.
        /// </summary>
        public static string direccionOficina {
            get {
                return ResourceManager.GetString("direccionOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direección Fiscal.
        /// </summary>
        public static string direcFiscal {
            get {
                return ResourceManager.GetString("direcFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutivo.
        /// </summary>
        public static string ejecutivo {
            get {
                return ResourceManager.GetString("ejecutivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutivo Contador.
        /// </summary>
        public static string ejecutivoContador {
            get {
                return ResourceManager.GetString("ejecutivoContador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejercicio.
        /// </summary>
        public static string ejercicio {
            get {
                return ResourceManager.GetString("ejercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string eliminar {
            get {
                return ResourceManager.GetString("eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Autorizador.
        /// </summary>
        public static string emailAutorizador {
            get {
                return ResourceManager.GetString("emailAutorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Validador.
        /// </summary>
        public static string emailValidador {
            get {
                return ResourceManager.GetString("emailValidador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Facturadora.
        /// </summary>
        public static string empFacturadora {
            get {
                return ResourceManager.GetString("empFacturadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string empresa {
            get {
                return ResourceManager.GetString("empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Facturadora.
        /// </summary>
        public static string empresaFacturadora {
            get {
                return ResourceManager.GetString("empresaFacturadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esquemas Pago.
        /// </summary>
        public static string esquema {
            get {
                return ResourceManager.GetString("esquema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esquemas.
        /// </summary>
        public static string Esquemas {
            get {
                return ResourceManager.GetString("Esquemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string estadoCivil {
            get {
                return ResourceManager.GetString("estadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string estatus {
            get {
                return ResourceManager.GetString("estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporta Reporte a Detalle.
        /// </summary>
        public static string excelDetalle {
            get {
                return ResourceManager.GetString("excelDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporta Reporte General.
        /// </summary>
        public static string excelGeneral {
            get {
                return ResourceManager.GetString("excelGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string factor {
            get {
                return ResourceManager.GetString("factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factores.
        /// </summary>
        public static string factores {
            get {
                return ResourceManager.GetString("factores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor de Integración.
        /// </summary>
        public static string factorIntegracion {
            get {
                return ResourceManager.GetString("factorIntegracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor Vacaciones.
        /// </summary>
        public static string factorVacaciones {
            get {
                return ResourceManager.GetString("factorVacaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar ingresar al SIAP.
        /// </summary>
        public static string failed_login {
            get {
                return ResourceManager.GetString("failed_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Alta.
        /// </summary>
        public static string fechaAlta {
            get {
                return ResourceManager.GetString("fechaAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Alta IMSS.
        /// </summary>
        public static string fechaAltaImss {
            get {
                return ResourceManager.GetString("fechaAltaImss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Baja.
        /// </summary>
        public static string fechaBaja {
            get {
                return ResourceManager.GetString("fechaBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Baja.
        /// </summary>
        public static string fechaFinal {
            get {
                return ResourceManager.GetString("fechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Final Vigencia.
        /// </summary>
        public static string fechaFinalVigencia {
            get {
                return ResourceManager.GetString("fechaFinalVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Firma.
        /// </summary>
        public static string fechaFirma {
            get {
                return ResourceManager.GetString("fechaFirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Inicio.
        /// </summary>
        public static string fechaInicio {
            get {
                return ResourceManager.GetString("fechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de inicio de contrato.
        /// </summary>
        public static string fechaInicioContrato {
            get {
                return ResourceManager.GetString("fechaInicioContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicial Vigencia.
        /// </summary>
        public static string fechaInicioVigencia {
            get {
                return ResourceManager.GetString("fechaInicioVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Modificación.
        /// </summary>
        public static string fechaModificacion {
            get {
                return ResourceManager.GetString("fechaModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento.
        /// </summary>
        public static string fechaNacimiento {
            get {
                return ResourceManager.GetString("fechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Registro.
        /// </summary>
        public static string fechaRegistro {
            get {
                return ResourceManager.GetString("fechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Solicitud.
        /// </summary>
        public static string fechaSolicitud {
            get {
                return ResourceManager.GetString("fechaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de término de contrato.
        /// </summary>
        public static string FechaTerminoContrato {
            get {
                return ResourceManager.GetString("FechaTerminoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F. Fin Desc..
        /// </summary>
        public static string fFinDescuento {
            get {
                return ResourceManager.GetString("fFinDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.Ini.Desc..
        /// </summary>
        public static string fInicioDescuento {
            get {
                return ResourceManager.GetString("fInicioDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmó.
        /// </summary>
        public static string firmo {
            get {
                return ResourceManager.GetString("firmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        public static string folioSolicitud {
            get {
                return ResourceManager.GetString("folioSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - SIAP Sistema de Administración de Personal IMSS.
        /// </summary>
        public static string footer_title {
            get {
                return ResourceManager.GetString("footer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Función.
        /// </summary>
        public static string funciones {
            get {
                return ResourceManager.GetString("funciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giro.
        /// </summary>
        public static string giro {
            get {
                return ResourceManager.GetString("giro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string grupo {
            get {
                return ResourceManager.GetString("grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIAP Web Site.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homoclave.
        /// </summary>
        public static string homoClave {
            get {
                return ResourceManager.GetString("homoClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFE Representante Legal.
        /// </summary>
        public static string ifeRepresentanteLegal {
            get {
                return ResourceManager.GetString("ifeRepresentanteLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicador.
        /// </summary>
        public static string indicador {
            get {
                return ResourceManager.GetString("indicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA Flujo.
        /// </summary>
        public static string ivaFlujo {
            get {
                return ResourceManager.GetString("ivaFlujo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA IAS.
        /// </summary>
        public static string ivaIAS {
            get {
                return ResourceManager.GetString("ivaIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA Nómina.
        /// </summary>
        public static string ivaNomina {
            get {
                return ResourceManager.GetString("ivaNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Email Auxiliar.
        /// </summary>
        public static string listaEmailAux {
            get {
                return ResourceManager.GetString("listaEmailAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Validación Cliente.
        /// </summary>
        public static string lvalCliente {
            get {
                return ResourceManager.GetString("lvalCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        public static string modificar {
            get {
                return ResourceManager.GetString("modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        public static string modulDes {
            get {
                return ResourceManager.GetString("modulDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo de la Baja.
        /// </summary>
        public static string motivoBaja {
            get {
                return ResourceManager.GetString("motivoBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        public static string municipio {
            get {
                return ResourceManager.GetString("municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturaleza.
        /// </summary>
        public static string naturaleza {
            get {
                return ResourceManager.GetString("naturaleza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Afiliacion.
        /// </summary>
        public static string noAfiliacion {
            get {
                return ResourceManager.GetString("noAfiliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Credito.
        /// </summary>
        public static string noCredito {
            get {
                return ResourceManager.GetString("noCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre(s).
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Completo.
        /// </summary>
        public static string nombreCompleto {
            get {
                return ResourceManager.GetString("nombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Corto.
        /// </summary>
        public static string nomCorto {
            get {
                return ResourceManager.GetString("nomCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Trabajadores.
        /// </summary>
        public static string noTrabajadores {
            get {
                return ResourceManager.GetString("noTrabajadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSS.
        /// </summary>
        public static string nss {
            get {
                return ResourceManager.GetString("nss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Cuenta.
        /// </summary>
        public static string numeroCuenta {
            get {
                return ResourceManager.GetString("numeroCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string observaciones {
            get {
                return ResourceManager.GetString("observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupación.
        /// </summary>
        public static string ocupacion {
            get {
                return ResourceManager.GetString("ocupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro.
        /// </summary>
        public static string parametro {
            get {
                return ResourceManager.GetString("parametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro ID.
        /// </summary>
        public static string parametroId {
            get {
                return ResourceManager.GetString("parametroId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parametros.
        /// </summary>
        public static string parametros {
            get {
                return ResourceManager.GetString("parametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrón.
        /// </summary>
        public static string patron {
            get {
                return ResourceManager.GetString("patron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo.
        /// </summary>
        public static string periodo {
            get {
                return ResourceManager.GetString("periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaza.
        /// </summary>
        public static string plaza {
            get {
                return ResourceManager.GetString("plaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaza ID.
        /// </summary>
        public static string plazaId {
            get {
                return ResourceManager.GetString("plazaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poder Representante Legal.
        /// </summary>
        public static string poderRepresentanteLegal {
            get {
                return ResourceManager.GetString("poderRepresentanteLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje.
        /// </summary>
        public static string porcentaje {
            get {
                return ResourceManager.GetString("porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición.
        /// </summary>
        public static string posicion {
            get {
                return ResourceManager.GetString("posicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prima Vacacional.
        /// </summary>
        public static string primaVacacional {
            get {
                return ResourceManager.GetString("primaVacacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto.
        /// </summary>
        public static string proyecto {
            get {
                return ResourceManager.GetString("proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Régimen Infonavit.
        /// </summary>
        public static string regInfonavit {
            get {
                return ResourceManager.GetString("regInfonavit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Patronal.
        /// </summary>
        public static string registroPatronal {
            get {
                return ResourceManager.GetString("registroPatronal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        public static string registros {
            get {
                return ResourceManager.GetString("registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string regresar {
            get {
                return ResourceManager.GetString("regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residencias.
        /// </summary>
        public static string residencia {
            get {
                return ResourceManager.GetString("residencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta Solicitud.
        /// </summary>
        public static string respuestaSolicitud {
            get {
                return ResourceManager.GetString("respuestaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retroceder.
        /// </summary>
        public static string retroceder {
            get {
                return ResourceManager.GetString("retroceder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC.
        /// </summary>
        public static string rfc {
            get {
                return ResourceManager.GetString("rfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string rol {
            get {
                return ResourceManager.GetString("rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salario Diario.
        /// </summary>
        public static string salarioDiario {
            get {
                return ResourceManager.GetString("salarioDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salario Real.
        /// </summary>
        public static string salarioReal {
            get {
                return ResourceManager.GetString("salarioReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        public static string sd {
            get {
                return ResourceManager.GetString("sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDI.
        /// </summary>
        public static string sdi {
            get {
                return ResourceManager.GetString("sdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string servicio {
            get {
                return ResourceManager.GetString("servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genero.
        /// </summary>
        public static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMDF.
        /// </summary>
        public static string smdf {
            get {
                return ResourceManager.GetString("smdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitó.
        /// </summary>
        public static string solicita {
            get {
                return ResourceManager.GetString("solicita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.
        /// </summary>
        public static string solicitud {
            get {
                return ResourceManager.GetString("solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Baja.
        /// </summary>
        public static string solicitudBaja {
            get {
                return ResourceManager.GetString("solicitudBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Modificación.
        /// </summary>
        public static string SolicitudModificacion {
            get {
                return ResourceManager.GetString("SolicitudModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir Acuse Masivo.
        /// </summary>
        public static string subirAcuseMax {
            get {
                return ResourceManager.GetString("subirAcuseMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testigo.
        /// </summary>
        public static string testigo {
            get {
                return ResourceManager.GetString("testigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Contrato.
        /// </summary>
        public static string tipoContrato {
            get {
                return ResourceManager.GetString("tipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Personal.
        /// </summary>
        public static string tipoPersonal {
            get {
                return ResourceManager.GetString("tipoPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Servicio.
        /// </summary>
        public static string tipoServicio {
            get {
                return ResourceManager.GetString("tipoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar a Excel.
        /// </summary>
        public static string toExcel {
            get {
                return ResourceManager.GetString("toExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        public static string ubicacion {
            get {
                return ResourceManager.GetString("ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Alta.
        /// </summary>
        public static string usuarioAlta {
            get {
                return ResourceManager.GetString("usuarioAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario ID.
        /// </summary>
        public static string usuarioID {
            get {
                return ResourceManager.GetString("usuarioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validador.
        /// </summary>
        public static string validador {
            get {
                return ResourceManager.GetString("validador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string valor {
            get {
                return ResourceManager.GetString("valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSM.
        /// </summary>
        public static string vsm {
            get {
                return ResourceManager.GetString("vsm", resourceCulture);
            }
        }
    }
}
